### ISSUE TITLE
Can't sign out

### ISSUE THREAD

**Issue by BernardZhao** [ocf/grafana#15]
I tried signing out of grafana, and it does not seem to work, I just get redirected to the same page still logged in. Not sure if this is a keycloak issue or what.

**Comment by dkess** [comment]
You would want to use the [`signout_redirect_url`](https://grafana.com/docs/grafana/latest/auth/overview/#url-redirect-after-signing-out) option here. Keycloak has a [logout endpoint](https://www.keycloak.org/docs/latest/securing_apps/index.html#logout) to point it to.

**Comment by BernardZhao** [comment]
Seems that this didn't work. The redirect url seems to be invalid

**Comment by BernardZhao** [comment]
I think im dumb, I was supposed to put a real `redirect_uri` instead of literally `encodedRedirectUri`. However, I don't really know what it should be, other than just `grafana.ocf.berkeley.edu`?

**Comment by BernardZhao** [comment]
I fixed this by just replacing it with the encoded original URL.
