### ISSUE TITLE
Upgrade to Grafana 7

### ISSUE THREAD

**Issue by nikhiljha** [ocf/grafana#17]
https://grafana.com/blog/2020/05/18/grafana-v7.0-released-new-plugin-architecture-visualizations-transformations-native-trace-support-and-more/

**Comment by dkess** [comment]
Based on the [upgrade notes](https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v7-0) it looks like we should be able to upgrade cleanly without any modifications.

**Comment by BernardZhao** [comment]
How should we go about upgrading? We already use the latest docker image, so shouldn't that just be 7.0.0? I looked on dockerhub and the latest image seemed to be updated 10 hours ago.

**Comment by nikhiljha** [comment]
@BernardZhao https://github.com/ocf/grafana/pull/18 like this
